sudo: false
language: cpp

matrix:
  include:
    # GCC 4.8
    - os: linux
      compiler: gcc
      dist: trusty
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8']
      env: TOOLSET=g++-4.8 CXX_VERSION=11

    - os: linux
      compiler: gcc
      dist: trusty
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8']
      env: TOOLSET=g++-4.8 CXX_VERSION=14

    # GCC 4.9
    - os: linux
      compiler: gcc
      dist: trusty
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']
      env: TOOLSET=g++-4.9 CXX_VERSION=11

    - os: linux
      compiler: gcc
      dist: trusty
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']
      env: TOOLSET=g++-4.9 CXX_VERSION=14

    # GCC 5
    - os: linux
      compiler: gcc
      dist: trusty
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env: TOOLSET=g++-5 CXX_VERSION=11

    - os: linux
      compiler: gcc
      dist: trusty
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env: TOOLSET=g++-5 CXX_VERSION=14

    # GCC 6
    - os: linux
      compiler: gcc
      dist: trusty
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env: TOOLSET=g++-6 CXX_VERSION=11

    - os: linux
      compiler: gcc
      dist: trusty
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env: TOOLSET=g++-6 CXX_VERSION=14

    # GCC 7
    - os: linux
      compiler: gcc
      dist: trusty
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env: TOOLSET=g++-7 CXX_VERSION=11

    - os: linux
      compiler: gcc
      dist: trusty
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env: TOOLSET=g++-7 CXX_VERSION=14

    # Clang 3.5
    - os: linux
      compiler: clang
      dist: trusty
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-3.5']
          packages: ['clang-3.5', 'libc++-dev']
      env: TOOLSET=clang++-3.5 CXX_VERSION=11

    - os: linux
      compiler: clang
      dist: trusty
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-3.5']
          packages: ['clang-3.5', 'libc++-dev']
      env: TOOLSET=clang++-3.5 CXX_VERSION=14

    # Clang 3.8
    - os: linux
      compiler: clang
      dist: trusty
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-3.8']
          packages: ['clang-3.8', 'libc++-dev']
      env: TOOLSET=clang++-3.8 CXX_VERSION=11

    - os: linux
      compiler: clang
      dist: trusty
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-3.8']
          packages: ['clang-3.8', 'libc++-dev']
      env: TOOLSET=clang++-3.8 CXX_VERSION=14

    # Clang 3.9
    - os: linux
      compiler: clang
      dist: trusty
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-3.9']
          packages: ['clang-3.9', 'libc++-dev']
      env: TOOLSET=clang++-3.9 CXX_VERSION=11

    - os: linux
      compiler: clang
      dist: trusty
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-3.9']
          packages: ['clang-3.9', 'libc++-dev']
      env: TOOLSET=clang++-3.9 CXX_VERSION=14

    # Clang 4.0
    - os: linux
      compiler: clang
      dist: trusty
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-4.0']
          packages: ['clang-4.0', 'libc++-dev']
      env: TOOLSET=clang++-4.0 CXX_VERSION=11

    - os: linux
      compiler: clang
      dist: trusty
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-4.0']
          packages: ['clang-4.0', 'libc++-dev']
      env: TOOLSET=clang++-4.0 CXX_VERSION=14

    # Clang 5.0
    - os: linux
      compiler: clang
      dist: trusty
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-5.0']
          packages: ['clang-5.0', 'libc++-dev']
      env: TOOLSET=clang++-5.0 CXX_VERSION=11

    - os: linux
      compiler: clang
      dist: trusty
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-5.0']
          packages: ['clang-5.0', 'libc++-dev']
      env: TOOLSET=clang++-5.0 CXX_VERSION=14

    # Xcode 6.4
    - os: osx
      compiler: clang
      osx_image: xcode6.4
      env: TOOLSET=clang++ CXX_VERSION=11

    - os: osx
      compiler: clang
      osx_image: xcode6.4
      env: TOOLSET=clang++ CXX_VERSION=14

    # Xcode 7.3
    - os: osx
      compiler: clang
      osx_image: xcode7.3
      env: TOOLSET=clang++ CXX_VERSION=11

    - os: osx
      compiler: clang
      osx_image: xcode7.3
      env: TOOLSET=clang++ CXX_VERSION=14

    # Xcode 8.3
    - os: osx
      compiler: clang
      osx_image: xcode8.3
      env: TOOLSET=clang++ CXX_VERSION=11

    - os: osx
      compiler: clang
      osx_image: xcode8.3
      env: TOOLSET=clang++ CXX_VERSION=14

# Install Catch
before_install:
 - wget https://github.com/philsquared/Catch/releases/download/v1.9.7/catch.hpp
 - export CATCH_ROOT="$PWD"
 - cd $TRAVIS_BUILD_DIR

# Prepare build
before_script:
  - mkdir build_debug
  - mkdir build_release
  - cd build_debug
  - cmake -D CMAKE_BUILD_TYPE=Debug -D CMAKE_CXX_COMPILER=$TOOLSET -D CXX_VERSION=${CXX_VERSION} -D CATCH_ROOT=$CATCH_ROOT ..
  - cd ../build_release
  - cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_CXX_COMPILER=$TOOLSET -D CXX_VERSION=${CXX_VERSION} -D CATCH_ROOT=$CATCH_ROOT ..
  - cd ..

script:
  - cd build_debug
  - make VERBOSE=1 run_tests
  - ctest --output-on-failure
  - cd ../build_release
  - make VERBOSE=1 run_tests
  - ctest --output-on-failure
